#!/usr/bin/env python3

import rospy
import actionlib
from chess_msgs.msg import PlayerInfo, ServerInfo
from chess_msgs.msg import QuickMatchAction

class QuickMatchServer(object):
    def __init__(self, name):
        self._action_name = name
        self._as = actionlib.SimpleActionServer(self._action_name, QuickMatchAction, execute_cb=self.execute_cb, auto_start = False)
        self._as.start()
      
    def execute_cb(self, goal):
        pass

server_pub = rospy.Publisher('server_info', ServerInfo, queue_size=10)

player_sub = rospy.Subscriber('player_info', PlayerInfo, None, queue_size=1)

rospy.init_node('server_node', anonymous = False)
quick_match_server = QuickMatchServer('quick_match')

rospy.spin()
