#!/usr/bin/env python3

'''
Node that communicates with Microcontroller and returns collated sensor data
'''

import rospy
from chess_msgs.msg import Grid

sensor_pub = rospy.Publisher('sensor_data', Grid, queue_size=10)

rospy.init_node('sensor_node', anonymous = True)

rospy.spin()
