#!/usr/bin/env python3

import rospy
from std_msgs.msg import String

test_pub = rospy.Publisher('test_cmd', String, queue_size=10)

rospy.init_node('test_node', anonymous=False)

print("Type 'q' to quit")
while (True):
    cmd = str(input("Cmd: "))
    if cmd == 'q':
        break
    msg = String()
    msg.data = cmd
    test_pub.publish(msg)
