#!/usr/bin/env python3

import rospy
from chess_msgs.msg import UIin, UIout

def UI_output_cb(msg):
    print(msg.data + '\n')

UI_input_pub = rospy.Publisher('UI_input', UIin, queue_size=10)

UI_output_sub = rospy.Subscriber('UI_output', UIout, UI_output_cb, queue_size=1)

rospy.init_node('UI_node', anonymous = True)

while (True):
    button = int(input("Press button: "))
    msg = UIin()
    msg.button = button
    UI_input_pub.publish(msg)

# rospy.spin()
